-- Borrower Master table for borrower-service
CREATE TABLE CDW_BORR_MSTR (
    BORR_ID         VARCHAR(20) PRIMARY KEY,
    BORR_FST_NM     VARCHAR(50),
    BORR_LST_NM     VARCHAR(50),
    BORR_MID_INIT   VARCHAR(1),
    BORR_SSN_ENCR   VARCHAR(100),
    BORR_DOB_DT     VARCHAR(10),
    BORR_ADDR_LN1   VARCHAR(100),
    BORR_ADDR_LN2   VARCHAR(100),
    BORR_CTY_NM     VARCHAR(50),
    BORR_ST_CD      VARCHAR(2),
    BORR_ZIP_CD     VARCHAR(10),
    BORR_PH_NBR     VARCHAR(15),
    BORR_EMAIL_ADDR VARCHAR(100),
    BORR_CRDT_SCR   VARCHAR(5),
    BORR_EMP_STAT   VARCHAR(20),
    BORR_ANN_INCM   VARCHAR(15),
    BORR_CRET_DT    VARCHAR(10),
    BORR_UPDT_DT    VARCHAR(10),
    BORR_STAT_CD    VARCHAR(5),
    BORR_REC_TYP    VARCHAR(10)
);
