-- Loan Products table for loan-service
CREATE TABLE CDW_LN_PROD (
    PROD_CD         VARCHAR(10) PRIMARY KEY,
    PROD_DESC_TXT   VARCHAR(200),
    PROD_TYP_CD     VARCHAR(5),
    PROD_TERM_MOS   VARCHAR(5),
    PROD_RT_TYP     VARCHAR(10),
    PROD_MIN_AMT    VARCHAR(15),
    PROD_MAX_AMT    VARCHAR(15),
    PROD_STAT_CD    VARCHAR(5),
    PROD_EFF_DT     VARCHAR(10),
    PROD_EXP_DT     VARCHAR(10)
);

-- Loan Accounts table for loan-service
CREATE TABLE CDW_LN_ACCT (
    LN_ACCT_NBR     VARCHAR(20) PRIMARY KEY,
    BORR_ID         VARCHAR(20),
    BORR_FST_NM     VARCHAR(50),
    BORR_LST_NM     VARCHAR(50),
    BORR_SSN_LST4   VARCHAR(4),
    PROD_CD         VARCHAR(10),
    LN_ORIG_AMT     VARCHAR(15),
    LN_CURR_BAL     VARCHAR(15),
    LN_INT_RT       VARCHAR(8),
    LN_TERM_MOS     VARCHAR(5),
    LN_PMT_AMT      VARCHAR(15),
    LN_ORIG_DT      VARCHAR(10),
    LN_MAT_DT       VARCHAR(10),
    LN_1ST_PMT_DT   VARCHAR(10),
    LN_NXT_PMT_DT   VARCHAR(10),
    LN_STAT_CD      VARCHAR(5),
    LN_DLQ_DAYS     VARCHAR(5),
    LN_ESCROW_BAL   VARCHAR(15),
    LN_LTV_PCT      VARCHAR(8),
    PROP_ADDR_LN1   VARCHAR(100),
    PROP_CTY_NM     VARCHAR(50),
    PROP_ST_CD      VARCHAR(2),
    PROP_ZIP_CD     VARCHAR(10),
    PROP_TYP_CD     VARCHAR(10),
    PROP_APRS_VAL   VARCHAR(15),
    LN_CRET_DT      VARCHAR(10),
    LN_UPDT_DT      VARCHAR(10)
);
